// Package e2ee encrypts session content end-to-end for relayed sessions,
// so the relay forwards ciphertext it cannot read.
//
// The 256-bit session key is generated by the host and shared with guests
// inside the join URL's fragment (#k=...). URL fragments are never sent
// over the network by HTTP clients, so the relay never sees the key.
// Frames are sealed with AES-256-GCM under a fresh random nonce, stored
// as nonce||ciphertext.
//
// Scope: terminal output and guest input are encrypted. Presence notices,
// guest names, the session code, and terminal size remain visible to the
// relay — it needs them to route and manage the session. Traffic timing
// and volume are visible too, as with any transport.
package e2ee

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"errors"
)

// KeySize is the session key length in bytes (AES-256).
const KeySize = 32

// NewKey generates a random session key.
func NewKey() ([]byte, error) {
	key := make([]byte, KeySize)
	if _, err := rand.Read(key); err != nil {
		return nil, err
	}
	return key, nil
}

// EncodeKey renders a key for use in a URL fragment.
func EncodeKey(key []byte) string {
	return base64.RawURLEncoding.EncodeToString(key)
}

// DecodeKey parses a key from a URL fragment.
func DecodeKey(s string) ([]byte, error) {
	key, err := base64.RawURLEncoding.DecodeString(s)
	if err != nil || len(key) != KeySize {
		return nil, errors.New("invalid session key in URL")
	}
	return key, nil
}

// Cipher seals and opens frame payloads.
type Cipher struct {
	aead cipher.AEAD
}

func New(key []byte) (*Cipher, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	return &Cipher{aead: aead}, nil
}

// Seal encrypts plain, returning nonce||ciphertext.
func (c *Cipher) Seal(plain []byte) []byte {
	nonce := make([]byte, c.aead.NonceSize())
	rand.Read(nonce)
	return c.aead.Seal(nonce, nonce, plain, nil)
}

// Open decrypts a nonce||ciphertext box.
func (c *Cipher) Open(box []byte) ([]byte, error) {
	ns := c.aead.NonceSize()
	if len(box) < ns {
		return nil, errors.New("ciphertext too short")
	}
	return c.aead.Open(nil, box[:ns], box[ns:], nil)
}
